### ISSUE TITLE
localhost

### ISSUE THREAD

**Issue by giesalabs** [aabeling/portscan#2]
hello,
on remote host:port it works, but i wasn't able to use on localhost or 127.0.0.1
i had try with:
```
    <tr>
      <td>localhost:15555</td>
      <td><span class="portscanner">localhost:15555</span></td>
    </tr>
    <tr>
      <td>localhost:80</td>
      <td><span class="portscanner">localhost:80</span></td>
    </tr>
    <tr>
      <td>127.0.0.1:15555</td>
      <td><span class="portscanner">127.0.0.1:15555</span></td>
    </tr>
    <tr>
      <td>127.0.0.1:80</td>
      <td><span class="portscanner">127.0.0.1:80</span></td>
    </tr>
```
it return back always as open port (yes, i have the 80 port open, but not the 15555), there is a way to check localhost?

sincerely G.

**Comment by aabeling** [comment]
No, that is not possible with this kind of check as far as I can see.
Please see my new notes in the readme.

Perhaps you try something else like https://github.com/baalexander/node-portscanner. On first glance this seems to support checks for localhost.

Best regards
Achim
